- app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/viewmodels/GardenPlantingListViewModel.kt
- Removed filtering on PlantAndGardenPlanting List in GardenFragment and placed inside ViewModel
> Refactor: Filtering on PlantAndGardenPlanting List

- app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantDiffCallback.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantingAdapter.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantDiffCallback.kt
- Changed the PlantAdapter and GardenPlantingAdapter to new list adapter which offers animation and diff util to improve performance.
- New DiffUtil implementation for PlantAdapter and GardenPlantAdapter having item amd content comparison.
> Refactor: Recycler View with List Adapter

- app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantingAdapter.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
- app/src/main/res/layout/list_item_plant.xml
According to ticket #20 as well.
> Refactored PlantAdapter with data-binding

- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
- app/src/main/res/layout/list_item_plant.xml
Set data binding variables in a `bind` method in the ViewHolder, following the guidance from the [Android Data Binding: RecyclerView article](https://medium.com/google-developers/android-data-binding-recyclerview-db7c40d9f0e4).
cc @XinyueZ
> Slight refactor to Plant adapter and data binding

- app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt
> Use Fragment viewLifecycleOwner

- app/src/main/res/layout/fragment_garden.xml
- app/src/main/res/layout/fragment_plant_list.xml
to fix overscroll being cut off
> Dont ClipToPadding

- README.md
- app/src/main/java/com/google/samples/apps/sunflower/GardenActivity.kt
GardenActivity and README cleanup
> Code cleanup

- app/build.gradle
- app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
- app/src/main/res/navigation/nav_garden.xml
- build.gradle
> Apply safe-args plugin

- app/src/main/java/com/google/samples/apps/sunflower/data/AppDatabase.kt
- app/src/main/java/com/google/samples/apps/sunflower/data/GardenPlanting.kt
> w:app/build/tmp/kapt3/stubs/debug/com/google/samples/apps/sunflower/data/GardenPlanting.java:15: warning: plant_id column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
> Fix Room FK warnings

- app/build.gradle
- app/src/androidTest/java/com/google/samples/apps/sunflower/PlantDetailFragmentTest.kt
- app/src/androidTest/java/com/google/samples/apps/sunflower/utilities/TestUtils.kt
- app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
- app/src/main/res/drawable/ic_share.xml
- app/src/main/res/menu/menu_plant_detail.xml
- app/src/main/res/values/strings.xml
> Share detail

- app/src/main/AndroidManifest.xml
- app/src/main/res/values/strings.xml
Also remove label from GardenActivity in AndroidManifest
> Add translation descriptions to String resources.

- app/src/androidTest/java/com/google/samples/apps/sunflower/PlantDetailFragmentTest.kt
- app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
- app/src/main/res/menu/menu_plant_detail.xml
- app/src/main/res/values/strings.xml
> Add translation_description to Share strings

- app/src/main/res/navigation/nav_garden.xml
- build.gradle
Also includes changing app:type to app:argType
> Update navigationVersion to alpha04

- app/src/androidTest/java/com/google/samples/apps/sunflower/PlantDetailFragmentTest.kt
> Fix test case

- build.gradle
#94 
- Updated constraint layout to 2.0.0-alpha2
> Constraint layout update

- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantDetailBindingAdapters.kt
- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/layout/fragment_plant_list.xml
- Rename functions to begin with `bind`
- Use `isGone` instead of `goneIf`
- Rename file
- Minor whitespace change
> Refactor data binding

- app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt
- app/src/main/res/layout/fragment_garden.xml
A future PR will add binding adapters.
> Convert GardenFragment and PlantListFragment to data binding

- app/src/androidTest/java/com/google/samples/apps/sunflower/data/GardenPlantingDaoTest.kt
- app/src/main/java/com/google/samples/apps/sunflower/data/GardenPlantingDao.kt
- app/src/main/java/com/google/samples/apps/sunflower/data/GardenPlantingRepository.kt
Add remove garden planting support in GardenPlantingDao. For feature #87.
> feat: add remove garden planting action in DAO

- app/src/androidTest/java/com/google/samples/apps/sunflower/utilities/TestUtils.kt
- app/src/main/java/com/google/samples/apps/sunflower/viewmodels/GardenPlantingListViewModel.kt
- Add explicit parameter to avoid shadowed `it`
- Remove unused withCollapsingToolbarTitle test helper method
> Minor code cleanup

- build.gradle
https://developer.android.com/topic/libraries/support-library/androidx-rn#1.0.0
> Update lib-dependencies for 1.0 release of AndroidX

- build.gradle
Check https://plugins.jetbrains.com/plugin/6954-kotlin
> Update kotlin 1.3.0-rc-116

- app/src/main/java/com/google/samples/apps/sunflower/data/Plant.kt
- app/src/test/java/com/google/samples/apps/sunflower/data/PlantTest.kt
- Optimize shouldBeWatered()
- Changes of test_shouldBeWatered()
> Fix/Optimize test_shouldBeWatered() which might break down test.

- app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
- build.gradle
Also updates calls to WorkManager's Result.
> Update versions of Room and WorkManager

- app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
- build.gradle
Also updates code to reflect API changes in WorkManager.
Fixes #260
> Update version of Room and WorkManager

- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantDetailBindingAdapters.kt
- app/src/main/res/layout/fragment_plant_detail.xml
This adds the ability to have HTML (including anchor tags) in
plant descriptions. This is in support of issue #264
Issue: #270
> Allow links in plant descriptions.

- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/values/dimens.xml
> Add padding to bottom of plant description for FAB

- app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
- build.gradle
Update also reflects API changes.
> Update WorkManager to 1.0.0-alpha13

- app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
- build.gradle
This includes updating the parameter for fromBundle().
> Update Navigation and Constraint Layout versions

- README.md
- build.gradle
Also update README to recommend using Android Studio 3.3.
> Update Gradle version to 3.3.0 to reflect Android Studio 3.3 release

- app/src/main/java/com/google/samples/apps/sunflower/utilities/InjectorUtils.kt
> Minor formatting fix.

- app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantingAdapter.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
- build.gradle
update roomVersion, workVersion, navigationVersion and uiAutomatorVersion
unit tests and UI tests pass
> update roomVersion, workVersion and uiAutomatorVersion

- build.gradle
Navigation to 1.0.0-beta04
WorkManager to 1.0.0-beta01
> Upgrade Navigation and Work versions

- app/src/main/res/anim/slide_in_right.xml
- app/src/main/res/anim/slide_out_left.xml
- app/src/main/res/anim/slide_out_right.xml
- app/src/main/res/values/anim.xml
> Extract value for slide animation

- app/src/main/res/values/anim.xml
New PR for the implemented fix for issue #265. The reduced animation time provides a seamless transition between fragments. This also includes the prep work from #330
> Reduced duration time of fragment transitions

- app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
- build.gradle
Updated WorkManager to 1.0.0-rc02 and refactored SeedDatabaseWorker to be a CoroutineWorker.
> Updated WorkManager to 1.0.0-rc02 and refactored SeedDatabaseWorker

- build.gradle
Related to #348 
@tiembo @nic0lette
> [UPDATE] lifecycle-lib to 2.1.0-alpha02

- app/build.gradle
- app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantDetailViewModel.kt
- build.gradle
This PR based on #347, please check #347 firstly and then consinder this one.
@tiembo @nic0lette
> [UPDATE/OPTIMISE] Introduce viewmodel-ktx and simplify PlantDetailViewMode

- app/src/main/res/values-fr/strings.xml
~~Note that while french locales are expecting %d for 0 and 1, in this context it is unnecessary (and wouldn't make sense).~~
~~Android Studio throws a warning but it doesn't prevent the developer from compiling. I'm not a fan of adding a silent ignore as they are usually easy to miss on code review.~~
EDIT: The CI tool rejected the pull request for the reason mentioned above so I modified the strings to support the placeholder in the singular form
> Added french locales

- app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
- app/src/main/res/menu/menu_garden_action_mode.xml
Change-Id: I818485adb8783f6707f30b892375ba00410e578d
> Add ActionMode framework.

- app/src/main/res/values/anim.xml
400ms is still way too long for animations. 200ms is fast, but still
noticeable.
Change-Id: Ic35d575adaadb3679927a54fbe9d9eb0ad91fef7
> Speed up animations.

- app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/viewmodels/GardenPlantingListViewModel.kt
- app/src/main/res/drawable/ic_delete_24dp.xml
- app/src/main/res/menu/menu_garden_action_mode.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
This updates the ActionMode in "My garden" to include an action to
remove selected plants from the garden. It doesn't actually remove the
plants yet though.
Change-Id: I8e125596d06818257d5965d31409d30daba95920
> Add a "remove plants" icon.

- README.md
This PR is regarding issue #418.
Changed reference to Android Studio from 
_"the latest version of Android Studio 3.3"_ 
to 
_"the latest version of Android Studio"._
> Updated README Android Studio reference.

- app/src/main/java/com/google/samples/apps/sunflower/ViewPagerFragment.kt
- app/src/main/res/layout/fragment_garden.xml
- app/src/main/res/layout/fragment_view_pager.xml
- app/src/main/res/values/dimens.xml
The title will now collapse in both the My Garden and Plant List screens.
> Add collapsing title to ViewPager

- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/values/dimens.xml
Also moves FAB anchor to app bar and increase header image height
> Add app bar to plant detail page

- app/src/main/res/values/dimens.xml
- app/src/main/res/values/integers.xml
Moved integer variable to its own file in values folder.
> Moved Grid Width to Integer.xml file.

- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Created Custom shapeappearance to plus button on detail page. Theme changes will follow in a future PR.
> Changed shape of FAB Plus button on detail page.

- app/src/main/res/layout/fragment_garden.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Added round corners to material themed Add Plant button on Garden page and changed color.
> Changed shape and color of add button

- app/src/main/res/layout/fragment_garden.xml
- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/layout/fragment_view_pager.xml
- app/src/main/res/layout/list_item_garden_planting.xml
- app/src/main/res/values/dimens.xml
Changed color and text styles to use theme attributes instead of constants to style.
> Changed to use theme attributes instead of constants

- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
- app/src/main/res/layout/fragment_garden.xml
- app/src/main/res/layout/fragment_plant_list.xml
- app/src/main/res/layout/plant_list_header.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Added top padding to My Garden page to separate cards from tabs. Added heading and padding for Plant List page.
> Added available plants header and padding to My Garden Page

- app/src/main/res/layout/fragment_plant_list.xml
- app/src/main/res/layout/plant_list_header.xml
Fixed side paddings for recycler view and fixed header padding.
> fixed padding in plant list page

- app/src/androidTest/java/com/google/samples/apps/sunflower/GardenActivityTest.kt
- app/src/androidTest/java/com/google/samples/apps/sunflower/PlantDetailFragmentTest.kt
Ignoring share button test for now, while the button is being redesigned.
> Update tests for the new UI interface

- app/src/main/java/com/google/samples/apps/sunflower/GardenActivity.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantDetailBindingAdapters.kt
- app/src/main/res/layout/fragment_garden.xml
- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/layout/fragment_view_pager.xml
- app/src/main/res/layout/list_item_garden_planting.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Added dark theme using Material.DayNight base theme.
> Added Dark Theme

- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/fragment_garden.xml
- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/layout/fragment_view_pager.xml
- app/src/main/res/layout/list_item_garden_planting.xml
- app/src/main/res/layout/list_item_plant.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/shape.xml
- app/src/main/res/values/styles.xml
Changed theme names to follow Material format and moved shape resources to shape.xml.
> Changed Theme and Shape Format

- app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
- app/src/main/res/animator/show_toolbar.xml
- app/src/main/res/layout/fragment_plant_detail.xml
Changed appbar elevation animation to use StateListAnimator instead of manually modifying the animation elements. Changed to use isTitleEnabled instead of adding and removing text.
> Show Toolbar Animation using StateListAnimator

- app/src/main/res/values-tr-rTR/strings.xml
Added Turkish strings as requested in #462
> Added Turkish strings.

- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-tr-rTR/strings.xml
Also removed duplicate app_name in Italian string resources
> Update Turkish string resources

- app/src/main/assets/plants.json
Was previously a picture of radishes.
> Update image of beet

- app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
- app/src/main/res/layout/fragment_plant_detail.xml
Also remove unused click listener
> Update FAB callback

- .google/packaging.yaml
- README.md
- app/src/test/java/com/google/samples/apps/sunflower/utilities/GrowZoneUtilTest.kt
> Update URLs for Sunflower due to repo move

- app/src/main/res/layout/fragment_plant_detail.xml
- app/src/main/res/layout/fragment_view_pager.xml
- app/src/main/res/navigation/nav_garden.xml
According to [official guide](https://developer.android.com/guide/topics/ui/declaring-layout?hl=JA#id), "@+id" should be used only in declarations. But this example uses "@+id" when referring other views. 
This PR doesn't contain commits affect to app behaviour.
> Replace inproper '@+id' to '@id' in xml files

- app/src/androidTest/java/com/google/samples/apps/sunflower/data/GardenPlantingDaoTest.kt
- app/src/androidTest/java/com/google/samples/apps/sunflower/data/PlantDaoTest.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantingAdapter.kt
- app/src/main/java/com/google/samples/apps/sunflower/utilities/GrowZoneUtil.kt
- app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantAndGardenPlantingsViewModel.kt
What I did:
1. run `Analyze` -> `Inspect code` in Android Studio.
2. fix all the Kotlin style issues.
> fix kotlin style issues

- build.gradle
appCompat, Constraint Layout, Glide
> Bump library versions

- app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/utilities/InjectorUtils.kt
- app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantListViewModel.kt
- app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantListViewModelFactory.kt
- build.gradle
Persist values in PlantListViewModel using SavedStateHandle
Fixes #572
> Update Navigation to 2.2.0 and add SavedStateHandle

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Reflects updating Android Studio to the latest stable version (3.6).
> Update AGP and Gradle wrapper

- app/src/main/res/values-ja/strings.xml
Translated ```(translate me)``` strings to Japanese and improved former translation slightly.
#462
> Translate strings to Japanese

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Reflects the latest Android Studio release.
Also use Gradle 6.1.1.
> Bump Gradle version to 4.0.0

- app/src/main/java/com/google/samples/apps/sunflower/utilities/InjectorUtils.kt
remove redundant local variable
> Minor code fix

- app/build.gradle
dataBinding.enabled is deprecated
> Update databinding gradle declaration

- build.gradle
SDK compile and target versions to 30
Gradle version to 4.0.1
> Update SDK and Gradle versions

- app/src/main/res/layout/activity_garden.xml
Host fragments with recommended `FragmentContainerView` in `activity_garden.xml` as described in:
https://developer.android.com/reference/androidx/fragment/app/FragmentContainerView
> Migrate to FragmentContainerView

- app/build.gradle
Update a little bit, which might be missed.
That's about using the Kotlin extension for the Paging Library.
> Update paging library for Kotlin extension

- app/src/androidTest/java/com/google/samples/apps/sunflower/data/GardenPlantingDaoTest.kt
- app/src/androidTest/java/com/google/samples/apps/sunflower/data/PlantDaoTest.kt
> Fix Dao tests to use Kotlin flow

- app/src/androidTest/assets/plants.json
- app/src/androidTest/java/com/google/samples/apps/sunflower/worker/SeedDatabaseWorkerTest.kt
Fix SeedWorkerTest after https://github.com/android/sunflower/pull/680
> Update SeedWorker test to fix breaking introduced in #680.

- app/src/main/res/values-sv-rSE/strings.xml
Add support for the Swedish language
> Add Swedish translation - sv-rSE

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/HomeViewPagerFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
- app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Upgrades Sunflower app to Compose 1.2.0-alpha07. Other changes:
* Remove Accompanist
* Use Gradle 7.2
> [Compose]: Upgrade to 1.2.0-alpha07

- README.md
- app/build.gradle
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
- app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantDetailBindingAdapters.kt
- app/src/main/java/com/google/samples/apps/sunflower/compose/ComposeViewHolder.kt
- app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt
- app/src/main/java/com/google/samples/apps/sunflower/compose/plantlist/PlantListItemView.kt
- build.gradle
Moving implementation in `compose_recyclerview` to `compose` branch so there's only one SoT for migrating to Compose.
> [Compose]: Implement RecyclerView item in Compose.

- app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt
- gradle/libs.versions.toml
> Fix %d appearing in watering needs string.

- app/build.gradle.kts
- app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt
- gradle/libs.versions.toml
> Use Compose BOM and fix image scrolling.

- app/src/main/java/com/google/samples/apps/sunflower/compose/garden/GardenScreen.kt
- gradle/libs.versions.toml
This landed yesterday as part of alpha03
> Call ReportDrawn instead of ReportDrawnWhen { true }

- app/build.gradle.kts
- gradle/libs.versions.toml
Remove the Truth library that is no longer in use.
> Remove unused Truth library

- app/src/main/java/com/google/samples/apps/sunflower/compose/SunflowerApp.kt
> Remove unused import

- app/src/main/java/com/google/samples/apps/sunflower/GardenActivity.kt
- app/src/main/java/com/google/samples/apps/sunflower/compose/SunflowerApp.kt
- app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt
Filter button was not working due to 2 separate PlantListViewModel instances. This fixes the filter button by using the same VM.
Fixes #854
> Fix filter button not working.

- app/src/main/java/com/google/samples/apps/sunflower/GardenActivity.kt
> Fix top app bar overlapping

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- CODE_OF_CONDUCT.md
Add templates to improve how issues/pull requests are created from the community. Also added our standard code of conduct file found in other Android sample repos.
> Add templates for filing issues and CODE_OF_CONDUCT.

- gradle/libs.versions.toml
AGP update in a separate PR #905
> Compose bom 2023.06.1

- .github/workflows/android.yml
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- macrobenchmark/build.gradle.kts
- macrobenchmark/src/main/AndroidManifest.xml
Updates to latest stable AGP + updates breaking changes
> Update AGP to 8.0.2

- .google/packaging.yaml
- app/src/androidTest/java/com/google/samples/apps/sunflower/data/GardenPlantingDaoTest.kt
- app/src/androidTest/java/com/google/samples/apps/sunflower/data/PlantDaoTest.kt
- app/src/main/java/com/google/samples/apps/sunflower/data/PlantDao.kt
- app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
- gradle/libs.versions.toml
PlantDao use Insert with provided on conflict strategy. With newer version of Room it's better to use Upsert in this case.
> Replace Insert with Upsert at PlantDao.

- app/build.gradle.kts
- app/proguard-rules.pro
- app/src/androidTest/java/com/google/samples/apps/sunflower/utilities/TestUtils.kt
- gradle/libs.versions.toml
Changes:
* Remove appcompat dependency
* Update proguard rules to not warn on okhttp classes
> Remove appcompat

- gradle/libs.versions.toml
Newer AGP version were available, so, I updated it.
> Update AGP to 8.1.2.

- .github/workflows/update_deps.yml
Change-Id: I7cd89bc19ed08eace4312a27245f92b4fe85d3ef
> Use secrets.GITHUB_TOKEN for update_deps workflow.
