android/sunflower

app/src/main/java/com/google/samples/apps/sunflower/viewmodels/GardenPlantingListViewModel.kt, app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantListViewModel.kt
These changes resolve issues #24 and #10 
Based on the ViewModel in the Arch [BasicSample](https://github.com/googlesamples/android-architecture-components/blob/master/BasicSample/app/src/main/java/com/example/android/persistence/viewmodel/ProductListViewModel.java). I tried to match the formatting/naming scheme from the PlantDetailViewModel.
=> Implement MediatorLiveData in ViewModels

app/build.gradle, build.gradle
This change includes a temporary workaround for a Kotlin 1.2.50 and DataBinding bug.
For more context see https://issuetracker.google.com/issues/110198434 and https://youtrack.jetbrains.com/issue/KT-24915#comment=27-2914947
=> Update Kotlin to 1.2.50 (with workarounds)

app/build.gradle, build.gradle
This PR also removes the temporary workaround for https://issuetracker.google.com/issues/110198434.
Fixes https://github.com/googlesamples/android-sunflower/issues/67
=> Update Android Gradle Plugin to 3.2.0-beta02

.gitignore
Some people would push a massive large file if it is not ignored.
=> Fix, ignore ktlint in .gitignore

app/src/main/res/layout/fragment_plant_detail.xml
Use "@id" may be more clear about FAB "layout_anchor" for existing view element. 
If someone remove "plant_detail_scrollview" view element and not change FAB, then compiler would report error to pointer out the reason for developer.
=> Refactor: code formatting

app/src/main/res/values/strings.xml
> app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2222: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
=> Fix position string warning

README.md
This pull request updates the ktlint installation instructions to match the [README](https://github.com/shyiko/ktlint/blob/master/README.md) of [ktlint](https://github.com/shyiko/ktlint). 
Specifically, we add `&& sudo mv ktlint /home/local/bin` to  `curl -sSLO https://github.com/shyiko/ktlint/releases/download/0.29.0/ktlint && chmod a+x ktlint`
Since ktlint was not in my `/home/local/bin` directory, on my setup of macOS using ZSH, I was unable to run `ktlint --apply-to-idea-project --android`
This PR adds installation instructions to avoid: `zsh: command not found: ktlint`
It also adds a blurb about installing via homebrew (also found from ktlint readme) which will by default put ktlint into `/home/local/bin`
=> Update ktlint Installation Instructions

app/src/main/java/com/google/samples/apps/sunflower/data/PlantAndGardenPlantings.kt, app/src/test/java/com/google/samples/apps/sunflower/data/PlantAndGardenPlantingTest.kt
Tiny change to PlantAndGardenPlantings to make the `plant` member
lateinit and non-optional (`Plant` vs `Plant?`).
=> Change "plant" to be non-optional.

app/src/main/res/layout/fragment_garden.xml
The warning log below is output now. 
```
w: warning: !hasPlantings is a boxed field but needs to be un-boxed to execute app:isGone. 
This may cause NPE so Data Binding will safely unbox it. 
You can change the expression and explicitly wrap !hasPlantings with safeUnbox() to prevent the warning
```
This field does not become null. I think that the primitive type is better.
=> use primitive type in databinding variable, not boxed type

app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
Per https://issuetracker.google.com/issues/123014564, this isn't necessary.
=> Omit .applicationContext in SeedDatabaseWorker

app/src/main/res/layout/fragment_plant_detail.xml
Changes include:
- Remove the duplicate toolbar in the collapsing layout
- Show plant name above watering details
- Change text size of plant description
We will look into a different layout when we start implementing Material design.
=> Fix double toolbar issue in Plant Details page

build.gradle
[CWE-829: Inclusion of Functionality from Untrusted Control Sphere](https://cwe.mitre.org/data/definitions/829.html)
[CWE-494: Download of Code Without Integrity Check](https://cwe.mitre.org/data/definitions/494.html)
The build files indicate that this project is resolving dependencies over HTTP instead of HTTPS. Any of these artifacts could have been MITM to maliciously compromise them and infect the build artifacts that were produced. Additionally, if any of these JARs or other dependencies were compromised, any developers using these could continue to be infected past updating to fix this.
This vulnerability has a CVSS v3.0 Base Score of 8.1/10
https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H
POC code has existed since 2014 to maliciously …
=> [SECURITY] Use HTTPS to download dependencies

app/src/main/res/values-de/strings.xml, app/src/main/res/values-it/strings.xml
=> Added Italian translation.

build.gradle
Sunflower is now using stable Kotlin resources.
=> Removing Kotlin EAP Maven entries

app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
This was introduced in [Navigation version 1.0.0-alpha10](https://developer.android.com/jetpack/androidx/releases/navigation#1.0.0-alpha10).
=> Use navArgs() instead of fromBundle() to retrieve args

app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
WorkManager v2.1 has deprecated coroutineContext. If you need to have
your CoroutineWorker run on a different Dispatcher, you can go to the
desired coroutineContext yourself in the body of the suspending
function.
=> Remove deprecated coroutineContext override.

app/build.gradle, app/src/androidTest/java/com/google/samples/apps/sunflower/worker/SeedDatabaseWorkerTest.kt, app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt, build.gradle
This add a test for the `SeedDatabaseWorker` using the `TestListenableWorkerBuilder` introduced in WorkManager v2.1.
=> Add WorkManager test for SeedDatabaseWorker

app/src/main/java/com/google/samples/apps/sunflower/data/AppDatabase.kt
Call `WorkManager.getInstance(context)` instead.
=> [FIX] Warning on call deprecated WorkManager.getInstance()

app/build.gradle, app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt, app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt, app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt, build.gradle
I replaced `ViewModelProviders.of(lifecycleOwner, factory).get(class)` with the `vimeModels` extension in `fragment-ktx`, which seems to be more in line with the `Kotlin` syntax, like this:
**From** 
```kotlin
val factory = InjectorUtils.provideGardenPlantingListViewModelFactory(requireContext())
val viewModel = ViewModelProviders.of(this, factory).get(GardenPlantingListViewModel::class.java)
```
**To**
```kotlin
private val viewModel: GardenPlantingListViewModel by viewModels {
InjectorUtils.provideGardenPlantingListViewModelFactory(requireContext())
}
```
Official documents can be viewed [here](https://developer.android.com/reference/kotlin/androidx/fragment/app/package-summary#viewmodels) .
=> Initialize the ViewModel using the extension function

app/src/main/java/com/google/samples/apps/sunflower/data/GardenPlantingDao.kt
The `getGardenPlantingForPlant` should return a `null` and then the `map` call or check (whatever) 
in `PlantDetailViewModel` could be meaningful and the warning of lint in IDE will be out.
=> [FIX] Ambiguity return of  getGardenPlantingForPlant in GardenPlantingDao

README.md
Updated two links, the Foundation link, and the UI link. I am concerned the new [link ](https://developer.android.com/jetpack/components) for Foundation may be a bit too generic.
=> Updated the Foundation link and the UI link.

README.md
This PR is regarding issue #419.
Removed reference and link to Google+ Community since Google+ is shutdown.
=> Removed Google+ community reference since Google+ is shutdown.

app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt, app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt, app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt
I used the extension function `observe` in `LiveData` to make adjustments to the code in the project, which seems to be more in line with the `Kotlin` syntax, like this:
**From** 
```kotlin
viewModel.gardenPlantings.observe(viewLifecycleOwner, Observer { plantings ->
binding.hasPlantings = !plantings.isNullOrEmpty()
})
```
**To**
```kotlin
viewModel.gardenPlantings.observe(viewLifecycleOwner) { plantings ->
binding.hasPlantings = !plantings.isNullOrEmpty()
}
```
=> Oberve LiveData with  Extension function

app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt, app/src/main/res/layout/fragment_garden.xml, app/src/main/res/navigation/nav_garden.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
When the user's garden is empty, add a button prompting them to navigate to the Plant List.
This also adds a new string and some placeholder string translations.
Updated styling will be implemented in a future commit.
=> Add button to navigate to Plant List

app/src/main/res/layout/fragment_garden.xml, app/src/main/res/layout/fragment_plant_list.xml, app/src/main/res/values/dimens.xml
Changed XML file of Plant List fragment to use GridLayout Manager instead of LinearLayoutManager, and changed GridLayout to use two columns instead of one. This is a setup PR to update the Plant List page to use Material Design cards.
=> Change Plant List Page to use GridLayout

app/src/main/assets/plants.json
The plant IDs now use the plant's binomial nomenclature as its unique ID.  This lays the groundwork for updating the plant database without having to recreate the database.
Fixes #271.
=> Use non-changing strings for plant IDs

app/src/main/res/layout/fragment_garden.xml, app/src/main/res/layout/list_item_garden_planting.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Used CustomCardView and material theme guidelines to turn plants on My Garden page into formatted cards. Added additional string constants to customize and theme headers that need translations. 
Before:
After:
=> Created Material-themed cards for My Garden Page

app/src/main/res/values/styles.xml
Fixed toolbar Text color, previously was pointing to wrong color element.
=> Toolbar text color

app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
I just rearranged the order of the method because it would be easier to see that the first called 'method' was in the first position. (just like GardenPlantingAdapter.kt)
=> rearrange method's order

app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
(I am practicing committing)
I liked the idea of using
`this::class.java.enclosingClass?.simpleName`
from within the companion object to define the tag value. however, i did research and found that using `simpleName` etc. can produce problems if you use obfuscation. 
further, the documentation example [here](https://developer.android.com/reference/android/util/Log) uses a string value. there would probably never be an issue, but since it is android's official app, let's be pedantic together :)
=> using const string for tag to prevent issues with obfuscation

app/src/main/java/com/google/samples/apps/sunflower/viewmodels/GardenPlantingListViewModelFactory.kt, app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantDetailViewModelFactory.kt
It makes more sense for custom ViewModel factories to implement `ViewModelProvider.Factory` instead of inheriting `ViewModelProvider.NewInstanceFactory` because they don’t use the implementations of NewInstanceFactory.
=> Use ViewModelProvider.Factory instead of ViewModelProvider.NewInstanceFactory

app/src/main/res/values-ru/strings.xml
Translate to Russian [#462](https://github.com/android/sunflower/issues/462)
=> Translate to russian.

build.gradle
Upgraded com.diffplug.gradle.spotless to version 4.3.0 to declare outputs to incremental task.
Previous version was 3.24.0. When building, it produced the following exception:
```bash
$ ./gradlew build
> Configure project :app
> Task :spotlessKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':spotlessKotlin'.
> You must declare outputs or use `TaskOutputs.upToDateWhen()` when using the incremental task API
```
This issue was fixed in Spotless 3.24.2 as per [Issue #427](https://github.com/diffplug/spotless/issues/427). I optimistically upgraded to the latest release (4.3.0, June 2020). There are also higher minor releases (3.30.0, May 2020) and patch releases (3.24.3, Sep 2019) available in …
=> Upgraded Spotless plugin to declare outputs

app/build.gradle
The stdlib library – starting from Kotlin 1.4.0, the stdlib dependency is added automatically.
You no longer need to declare a dependency on the stdlib library in any Kotlin Gradle project, including a multiplatform one. The dependency is added by default.
=> Remove kotlin stdlib dependency

app/src/main/res/layout/fragment_view_pager.xml
Issue link: https://github.com/android/sunflower/issues/656
Before changes:
After changes:
=> Fixed title in the Toolbar is not in the center in horizontal #656

app/src/main/res/layout/fragment_plant_detail.xml, app/src/main/res/layout/fragment_view_pager.xml
Renamed view name in fragment_view_pager from `<androidx.appcompat.widget.Toolbar>` to `<com.google.android.material.appbar.MaterialToolbar>`
I think It seems that the existing toolbar is the one of Material Design.
According to [Material Design Guide - app bars top documentation](https://material.io/develop/android/components/app-bars-top), It is using `<com.google.android.material.appbar.MaterialToolbar>` instead of `<androidx.appcompat.widget.Toolbar>`.
And, [MaterialToolbar documentation](https://developer.android.com/reference/com/google/android/material/appbar/MaterialToolbar) also announces this.
So I tried to change. Please review. Thank you😊
=> Rename view name in fragment_view_pager.xml

app/build.gradle
Not only is the kotlin-android-extensions deprecated, but it's also not being used in this project.
=> chore: remove deprecated kotlin-android-extensions plugin

app/build.gradle
`=` is redundant here. It is slightly better to omit it for simplicity, as in the [official documentation](https://developer.android.com/topic/libraries/data-binding/start).
=> Replace "dataBinding = true" with "dataBinding true" in app/build.gradle

app/src/androidTest/java/com/google/samples/apps/sunflower/GardenActivityTest.kt, app/src/androidTest/java/com/google/samples/apps/sunflower/MainCoroutineRule.kt, app/src/androidTest/java/com/google/samples/apps/sunflower/data/PlantDaoTest.kt, app/src/androidTest/java/com/google/samples/apps/sunflower/viewmodels/PlantDetailViewModelTest.kt, app/src/androidTest/java/com/google/samples/apps/sunflower/worker/SeedDatabaseWorkerTest.kt, app/src/test/java/com/google/samples/apps/sunflower/data/GardenPlantingTest.kt
- replace junit `assertThat` with hamcrest one
- replace `ActivityTestRule` with `ActivityScenarioRule`
- replace `TestCoroutineDispatcher` with `TestDispatcher`
Note: if the test can not be run at all, downgrade **espresso** to 3.3.0 as i mentioned [here](https://github.com/android/sunflower/issues/764).
=> Update deprecated testing

app/build.gradle, build.gradle
Updating the Espresso to 3.4.0 broke the instrumented tests as in
https://github.com/android/android-test/issues/861
This PR explicitly specifies the version of the accessibility-test-framework
Fixes #764 
But #783 still persists even after this fix.
=> Fix the issue instrumented tests can't be executed

.github/workflows/android.yml
Context:
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
=> Update the environment of the build in GitHub Actions.

app/build.gradle.kts
Demonstrate removing META-INF version files in release mode. These version files are required in debug mode for layout inspector to work.
=> Exclude version files in release mode.

app/build.gradle.kts, app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt, app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt, app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt, gradle/libs.versions.toml
See https://github.com/google/accompanist/pull/1410
=> Migrate usages of MdcTheme to Accompanist

app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt
This PR will fix the deprecation of the observe extension method in PlantListFragment because the observe extension method is no longer required when using Kotlin 1.4. I have fixed it by removing the ` import androidx.lifecycle.observe `. 
[#878](https://github.com/android/sunflower/issues/878)
This PR is part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative
=> Fix the deprecation of the observe extension method in PlantListFragment

gradle/libs.versions.toml
I've updated the compose activity dependency version to 1.7.2
#853
This change prevents the removeReporter() called when all reporters have already been removed exception which causes the app crashes. See #853 for more information.
The 1.7.2 version prevents this crash by fixing the bug which is caused by onDismiss and observeReporter().
This PR is part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative
=> [Fix] removeReporter App Crashes 

app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt
This fixes #871 
This pull request addresses the issue of the ``pagerState`` resetting to 1 when navigating back from the plant detail page to the home page in the ``HomeScreen``. The ``pagerState`` is responsible for managing the current page in the home screen pager.
Each time ``HomeScreen`` is recomposed, the pagerState resets
I have solved the issue by moving the pagerState outside of the HomeScreen composable and making it a remember-composable at a higher level in the composable hierarchy. This way, the ``pagerState`` will be preserved even when the HomeScreen recomposes.
``PART OF GTC OPEN SOURCE INTIATIVE``
=> Fix pagerState

README.md
We use Apache license but we do not license software to apache foundation. Also no license info is needed in the readme file
=> Fix wrong licensing information.

.google/packaging.yaml
This project doesn't use Jetpack DataStore, but while it had the JetpackDataStore tag it was incorrectly recommended as a hint in the DataStore documentation. 
I remove tag Jetpack DataStore.
=> Fix Incorrect packaging.yaml #898 

app/src/main/res/layout/fragment_view_pager.xml
If menu icon is added to top app bar, there is a problem that the title are out of alignment
Like this
Take TextView out of Toolbar's child
=> Fix app bar title alignment to center

app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt
=> Replaced TopAppBar with CenterAlignedTopAppBar, Fix issue #857 

.github/ci-gradle.properties, .github/workflows/update_deps.yml, app/src/main/java/com/google/samples/apps/sunflower/MainApplication.kt, build.gradle.kts, buildscripts/init.gradle.kts, buildscripts/toml-updater-config.gradle, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, macrobenchmark/src/main/java/com/google/samples/apps/sunflower/macrobenchmark/BaselineProfileGenerator.kt
Changes:
* Update dependencies to latest and update breaking changes
* Add a new workflow that runs every month to check for updated dependencies (it can also be manually run)
=> Update dependencies and add update deps workflow

app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantDetailViewModel.kt
ViewModel is used in PlantDetailsScreen not PlantDetailFragment. Probably missed during migration from Fragments to Compose.
=> comment update

.github/workflows/update_deps.yml
Change-Id: I7ae56528ce0a741aec27aee76951790450176011
=> Update secret used by update_deps workflow.

app/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
On #972 
- Updated Kotlin version to 2.0.0
- Migrated compose compiler
=> Update Kotlin v2.0 & migrated Compose compiler

app/build.gradle.kts, app/src/main/java/com/google/samples/apps/sunflower/compose/garden/GardenScreen.kt, app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt, app/src/main/java/com/google/samples/apps/sunflower/viewmodels/GardenPlantingListViewModel.kt, app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantDetailViewModel.kt, gradle/libs.versions.toml
Use collectAsStateWithLifecycle to save app resources when you don't need them, 
such as when they're in the background. 
The following tasks have been applied.
1. add dependency `androidx.lifecycle.lifecycle-runtime-compose`
2. modify flow to stateFlow in viewModel
3. modify collectAsState to collectAsStateWithLifecycle in Composable Screen
=> Modify collectAsState to collectAsStateWithLifecycle

README.md
Make a note section easily find first in sight.
[Preivew](https://github.com/Jaehwa-Noh/sunflower/tree/update-readme?tab=readme-ov-file#features) is here.
> [!Note]
> To see the original View implementation of Sunflower, checkout the [`views`](https://github.com/android/sunflower/tree/views) branch.
> [!Note]
> As Compose cannot render HTML code in `Text` yet. The 
> `AndroidViewBinding` API is used to embed a `TextView` in Compose. See the 
> `PlantDescription` composable in the
> [PlantDetailView file](app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt).
=> Improve `README.md` Noticeability.

README.md
We are prioritizing a smaller set of Compose samples.
Please see https://github.com/android/compose-samples for a more up-to-date set of Compose showcases, or https://github.com/android/snippets
We encourage you to fork this sample if you are still finding it valuable for your use case, however - no more updates will be made to this repository.
=> Update README.md to deprecate Sunflower
